version: '3'
services:
    app:
        build:
            context: .
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        networks:
            - my-network
    db:
        image: mysql:8
        container_name: myserver
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_DATABASE: "${DB_DATABASE}"
        networks:
            - my-network
    phpmyadmin:
        image: phpmyadmin:latest
        depends_on:
            - db
        ports:
            - 8090:80
        environment:
            PMA_HOST: db
        networks:
            - my-network
networks:
    my-network:
        driver: bridge
